.github/PULL_REQUEST_TEMPLATE.md, .github/public_PULL_REQUEST_TEMPLATE.md
- Create PR template
- Rename previous iteration of PR template to allow reversion later
- Story: [ADB-73](https://sparkbox.atlassian.net/browse/ADB-73)
- Before: https://main--aem-block-collection--adobe.hlx.page
- After: https://ADB-73--aem-block-collection--adobe.hlx.page
1. Review `.github/PULL_REQUEST_TEMPLATE.md`
2. That's it, really. I'm open to thoughts/feedback/suggestions.
=> chore: create PR template

tests/pattern-library.test.js
- Adds Pattern Library Page: https://main--adobe-design-website--adobe.aem.live/pattern-library/
- Adds initial pattern library puppeteer test
- Designs: [Figma](FIGMA_URL)
- Story: [ADB-104](https://sparkbox.atlassian.net/browse/ADB-104)
- Before: https://main--adobe-design-website--adobe.aem.page
- After: https://ADB-104-pattern-library--adobe-design-website--adobe.aem.page/pattern-library/
2. Pull down all related branches.
3. Verify puppeteer test created for pattern library page
4. Verify tests pass for pattern library test
=> chore: Adds Pattern Library page and puppeteer test

.husky/_/pre-push, package-lock.json, package.json
- adds husky
- adds pre-push hook to run` npm run lint` and `npm run test` on `git push`
- Designs: [Figma](FIGMA_URL)
- Story: [ADB-212](https://sparkbox.atlassian.net/browse/ADB-212)
- After: https://ADB-212-git-push-linting-tests--adobe-design-website--adobe.aem.page/
2. Pull down this branch
3. Create a linting error and failing test locally
4. Create a temporary commit and attempt to push to this branch
5. Verify you are not able to push to this branch until linting and tests are passed
=> feat: add husky for linting/tests on git push

blocks/hero/hero.css, styles/base.css, styles/styles.css
- added new colors
- added theme for new gradient
- fixed a little hero thing so the text looks better
- changed how multi-tone works because both are in both modes 
- updated docs with new theme
- Designs: [Figma](https://www.figma.com/design/QzvOszpLGT7fwSd6N7gaDW/Adobe-Design?node-id=475-8539&t=OFdW9ZPrD607t7y0-0)
- Story: [ADB-215](https://sparkbox.atlassian.net/browse/ADB-215)
- After: https://feat-color-updates--adobe-design-website--adobe.aem.page/
=> feat(styles): colors match designs

package-lock.json, package.json
- Adjust package file to house correct information
- After: https://chore-package-detail--adobe-design-website--adobe.aem.page/
=> chore: package file has correct information

.stylelintrc.json, blocks/quote/quote.css, blocks/quote/quote.js, blocks/quote/quote.test.js
- Refactors and restyles Blockquote component
- Adds tests
- Adds a stylelint config to remove rule causing linting errors in `base.css`
*Jelly providing additional designs for attribution
- Designs: [Figma](https://www.figma.com/design/QzvOszpLGT7fwSd6N7gaDW/Adobe-Design?node-id=718-14332&m=dev)
- Story: [ADB-173](https://sparkbox.atlassian.net/browse/ADB-173)
- After: https://ADb-173-blockquote--adobe-design-website--adobe.aem.page/
2. Pull down all related branches.
3. Verify Blockquote align with [mockups](https://www.figma.com/design/QzvOszpLGT7fwSd6N7gaDW/Adobe-Design?node-id=718-14332&m=dev)
4. Verify all tests are passing
=> feat: Blockquote

blocks/button-group/button-group.css, blocks/button-group/button-group.js, blocks/button-group/button-group.test.js, scripts/aem.js, scripts/scripts.js, styles/base.css, styles/styles.css
- Remove automatic link styling as buttons
- Create button styles
- Create button-group block
- Designs: [Figma](https://www.figma.com/design/QzvOszpLGT7fwSd6N7gaDW/Adobe-Design?node-id=2-1827&t=bfZ2EswyxBZVw93K-1)
- Stories: [ADB-163](https://sparkbox.atlassian.net/browse/ADB-163), [ADB-164](https://sparkbox.atlassian.net/browse/ADB-164)
- Before: https://main--adobe-design-website--adobe.aem.page/pattern-library/
- After: https://feat-button-group--adobe-design-website--adobe.aem.page/pattern-library/
1. Visit the [branch preview page](https://feat-button-group--adobe-design-website--adobe.aem.page/pattern-library/)
2. Scroll down to the Button-Group section
3. Verify the Button-Group is responsive (`flex-direction: column` on mobile screens, `flex-direction: row` on screens larger than …
=> feat: button styles and button-group

blocks/accordion/accordion.test.js, blocks/cards/cards.test.js, blocks/columns/columns.css, blocks/columns/columns.js, blocks/columns/columns.test.js, blocks/filter-group/filter-group.css, blocks/filter-group/filter-group.js, blocks/footer/footer.test.js, blocks/form/form-fields.js, blocks/form/form.test.js, blocks/fragment/fragment.test.js, blocks/header/header.css, blocks/header/header.js, blocks/header/header.test.js, blocks/hero/hero.css, blocks/hero/hero.test.js, blocks/tabs/tabs.test.js, scripts/aem.js
Removes the `-wrapper` class by default and resolves tests and styling. This makes our code more robust and semantic moving forward. Where wrapper classes are essential, we add them at the block level. 
- Story: [ADB-224](https://sparkbox.atlassian.net/browse/ADB-224)
- After: https://refactor-wrappers--adobe-design-website--adobe.aem.page/
1. Pull down all related branches.
2. Pull up [this version of the sit](https://refactor-wrappers--adobe-design-website--adobe.aem.page/)e with [deployed main](https://main--adobe-design-website--adobe.aem.page/pattern-library/) - everything should function the same. 
3. The one standout is the hero, which I did not make a new decorate function just to …
=> feat: containers have wrapper classes that align with BEM best practice

blocks/filter-group/filter-group.css, styles/styles.css
- Creates global focus styles
- Removes focus styles from button and filters
- Story: [ADB-186](https://sparkbox.atlassian.net/browse/ADB-186)
- After: https://focus-styles--adobe-design-website--adobe.aem.page/
1. Use the keyboard to test the focus styles. 
2. Also click stuff
=> feat: global focus indicator

blocks/cards/cards.test.js, blocks/link-list/link-list.js, blocks/link-list/link-list.test.js, scripts/aem.js, scripts/scripts.js, styles/styles.css
- Link-List no longer takes a title and an optional link
- `.grid-item--50` takes up the entire grid on screen sizes below tablet size
- `decorateLayouts()` function supports two-up layout
- horizontal rule tags match `-NAME-` pattern
- Designs: [Figma](https://www.figma.com/design/QzvOszpLGT7fwSd6N7gaDW/Adobe-Design?node-id=841-5194&t=7bVdF3gMQ6LJqeNY-1) (on the homepage, an example of this layout is the Adobe Design News section, which contains a Link-List and Callout block)
- Story: [ADB-181](https://sparkbox.atlassian.net/browse/ADB-181)
- Before: https://main--adobe-design-website--adobe.aem.page/pattern-library/layouts
- After: https://feat-two-up-layout--adobe-design-website--adobe.aem.page/pattern-library/layouts
1. Visit the [Layout page on the branch …
=> feat: two-up layout

styles/base.css
Fixes the values of a few custom properties in `base.css` that were referencing undefined tokens ending in `-rgb`. Also replaces the legacy `rgba()` alias with `rgb()` in a few locations.
- After: https://fix-rgb-base-tokens--adobe-design-website--adobe.aem.page/
1. `base.css` no longer references undefined rgb tokens `--spectrum-white-rgb` and `--spectrum-black-rgb`, and updated values look correct.
---
=> fix: replace reference to undefined rgb tokens

blocks/filter-group/filter-group.css, blocks/footer/footer.css, blocks/header/header.css, blocks/header/header.js, blocks/header/nav-toolbar.js, blocks/search/search.css, blocks/search/search.js, blocks/search/search.test.js, head.html, scripts/scripts.js, styles/base.css, styles/styles.css
- Refactor Search
- Create nav tools partial and move the color scheme toggle in there
- Create toggle styles
- Replace theme select to use the toggle, with system default on load (thanks for the pair @arnest00)
- Story: [ADB-159](https://sparkbox.atlassian.net/browse/ADB-159)
- Story: [ADB-214](https://sparkbox.atlassian.net/browse/ADB-214)
- After: https://nav-toolbar--adobe-design-website--adobe.aem.page/
1. Buckle in, this one is a lot of code (maybe get a snack, little protein, there's a woman who puts peanut butter and jelly on boiled eggs, we could try that)
1. Pull up the home page and test from tablet to desktop, noting that mobile …
=> feat: nav toolbar

blocks/page-header/page-header.css, blocks/page-header/page-header.js, blocks/page-header/page-header.test.js, styles/styles.css
- page header component
- Story: [ADB-162](https://sparkbox.atlassian.net/browse/ADB-162)
- After: https://page-header--adobe-design-website--adobe.aem.page/
1. The page header is easiest to review on the homepage. 
1. Head to / and see the new heading content. 
1. Note that the background image will be done in a different ticket. 
1. The page header is also included, with documentation, on the pattern library page.
1. Review the simpler version of the header to note a change in description text, button style, and button alt text.
1. Let Catherine know she's really cool for figuring this bit out. 
1. For the pages with long body copy as a …
=> feat: page header

blocks/card/card.css, blocks/footer/footer.css, blocks/small-screen-cta/small-screen-cta.css, blocks/small-screen-cta/small-screen-cta.js, blocks/small-screen-cta/small-screen-cta.test.js, styles/base.css, styles/styles.css
- built a CTA for use on the homepage
- buttons were looking a little slim, so helped them with some gains
- Story: [ADB-231](https://sparkbox.atlassian.net/browse/ADB-231)
- Before: https://main--adobe-design-website--adobe.aem.page/pattern-library/
- After: https://small-screen-cta--adobe-design-website--adobe.aem.page/pattern-library/
1. Go to the pattern library on the smalllllllest screen ✅ CTA is just a button (it's under "small screen cta" on the pattern library page)
1. Increase to middle size screen ✅ CTA has a background and description now 
1. Increase to larges screen, very very big ✅ no CTA it's outta here like me on thursday morning when PTO hits
=> feat: small screen CTA

blocks/header/header.js
Fix "was used before it was defined" warnings in the nav, where three functions are all referencing each other. Changing the order was not possible so this is fixed by declaring the variables first.
Original warning:
```
blocks/header/header.js
71:40  warning  'closeNavMenu' was used before it was defined     no-use-before-define
78:42  warning  'handleEscapeKey' was used before it was defined  no-use-before-define
103:45  warning  'handleEscapeKey' was used before it was defined  no-use-before-define
```
- After: https://chore-lint-defined-before--adobe-design-website--adobe.aem.page/
1. `npm run lint` no longer shows warnings.
2. Nav open/close/esc functionality remains the same.
=> chore: nav - fix lint defined before use warnings

assets/themes/shapes.js, blocks/header/header.js, scripts/aem.js, scripts/modules/themeBackgrounds.js, scripts/scripts.js, styles/base.css, styles/styles.css
Changes to implementation of gradients and themes:
- Theme names no longer need to be prefixed with `theme-` in the content metadata. Theme names from metadata are now automatically prefixed with `theme--` and the generic `theme` class is also added along with it to the body.
- Gradients were previously starting higher up than designed, because of the area underneath the sticky nav. To keep the existing gradients without having to change all of their colors, an overscroll color matching the starting gradient has been added 64px above using a second `linear-gradient`, since this area is visible on scroll bounce.
- SVGs used on the hero background areas can't be used as a URL in a `background-image`, or as an image source, because we need access to change the colors with CSS between both …
=> feat: gradients and theme change, and rounded diamond themes

assets/themes/shapes.js, blocks/hero/hero.test.js, scripts/modules/themeBackgrounds.js, styles/base.css, styles/styles.css
**Adds article themes**
Includes all designed themes available for the article pages.
- blue 
- cyan 
- indigo 
- fuchsia 
- red 
- seafoam 
- cinnamon 
- orange
- no-color _(same as w/o any theme but included in case of wanting to specify in the metadata)_
The hero themes now all have the following names:
- hero-indigo
- hero-green
- hero-seafoam
- hero-blue-green-wave
- hero-blue-circles
**Gradients refactor**
Refactors gradients and their usage with themes to slim down repetitive code and to only include the needed gradients. Almost all gradients outside SVGs are linear and can be defined by just the start color. The overscroll color has been made part of the same `linear-gradient` instead of a separate one.
- Designs: [Figma](https://www.figma.com/design/mf1X2eC29hxagQcYF2juqW/WIP_Adob …
=> feat: add additional gradient themes

helix-query.yaml
Add all needed properties to the `helix-query.yaml` config, since automatic properties no longer occur once a custom configuration is used.
Renames `date` to `publicationDate` and adds an additional `publicationTimestamp` that parses the timestamp. All articles have their "Publication Date" entered as metadata that is formatted like "June 1, 2025".
- After: https://feat-query-properties--adobe-design-website--adobe.aem.page/
- You can pull down and run `aem up --print-index`
- Visit an ideas page (https://github.com/adobe/adobe-design-website/pull/99) to see the fields logged out. The two date fields look correct. As do path, title, image, author, description, tag.
- Note: lastModified is appearing blank in this testing tool, …
=> feat: add all properties to helix-query config

blocks/link-list/link-list.css, blocks/link-list/link-list.js
- link-list matches height of two-up layout container
- link-list with jobs variant support for two-column in-between layout
- Designs: [Figma](https://www.figma.com/design/QzvOszpLGT7fwSd6N7gaDW/Adobe-Design?node-id=841-5194&t=dnWI2iGDhBVC4PPb-1)
- Story: [ADB-242](https://sparkbox.atlassian.net/browse/ADB-242)
- After: https://fix-link-list-breakpoints--adobe-design-website--adobe.aem.page/
1. Navigate to the homepage on the feature branch
2. Scroll to the "Adobe Design News" section
3. Verify the link-list block matches the height of the callout
4. Scroll to the bottom of the page, to the "Design your career at Adobe" section
5. Verify on a screen size >48rem and <80rem, there is a new layout with two columns of career …
=> fix: link-list behavior

blocks/article-header/article-header.css, blocks/button-group/button-group.css, blocks/callout/callout.css, blocks/feature-layout/feature-layout.css, blocks/feature-layout/feature-layout.js, blocks/job-list/job-list.css, blocks/link-list/link-list.css, blocks/link-list/link-list.js, blocks/page-header/page-header.css, blocks/recent-ideas/recent-ideas.js, blocks/recent-ideas/recent-ideas.test.js, blocks/section-header/section-header.css, blocks/section-header/section-header.js, blocks/small-screen-cta/small-screen-cta.css, styles/global-blocks.css, styles/styles.css
Global
Story Packs
Homepage
Article
- Story: [ADB-247](https://sparkbox.atlassian.net/browse/ADB-247)
- Story: [ADB-251](https://sparkbox.atlassian.net/browse/ADB-251)
- After: https://breakpoints--adobe-design-website--adobe.aem.page/
@arnest00 I honestly touched a whole bunch of stuff, go through the list and i'll try to annotate the changes with where to test them
=> feat: breakpoint and spacing adjustments

styles/styles.css
Increase inline padding on buttons globally from `1.0rem` to `1.25rem`.
- Story: [ADB-255](https://sparkbox.atlassian.net/browse/ADB-255)
- After: https://fix-button-padding--adobe-design-website--adobe.aem.page/
2. Review buttons in use at https://fix-button-padding--adobe-design-website--adobe.aem.page/ and make sure the padding has increased and nothing looks off.
---
We should aim to support the latest version of the listed browsers. For older versions or other browsers not on the list, content should be accessible, even if it doesn't completely match the designs.
Developers should test as they work in the browsers available on their machines. If they have access to other devices to …
=> fix: increase button inline padding

blocks/ideas/ideas.js, scripts/scripts.js
- update ideas block button label to "Load more"
- run `buildArticlePage()` only on appearance of article-header block
- Story: [ADB-262](https://sparkbox.atlassian.net/browse/ADB-262)
- After: https://fix-ideas-route--adobe-design-website--adobe.aem.page/
1. Navigate to the tag page for "design systems" at [/ideas/design-systems](https://fix-ideas-route--adobe-design-website--adobe.aem.page/ideas/design-systems)
2. Scroll down and verify the updated button label
3. Open the page's associated Sharepoint document - the page should be using the ideas block to fetch articles with the "design systems" tag
4. Navigate to the story pack page for "Designing Design Systems" at …
=> fix: ideas route issues

blocks/button-group/button-group.css, blocks/card/card.css, blocks/constrained-text/constrained-text.css, blocks/fragment/fragment.css, blocks/image-with-caption/image-with-caption.css, blocks/job-listing/job-listing.css, blocks/recent-ideas/recent-ideas.css, blocks/search/search.css, scripts/aem.js, scripts/helpers/blockSettings.js, scripts/helpers/index.js
Reduces the number of fetch requests by no longer trying to fetch block CSS for blocks that do not have CSS files.
Removes empty CSS files that were only there to prevent loading errors.
📉 Reduces number of CSS file fetch requests on the pattern library by 25%.
**Details:** This creates a block settings array that lists all blocks that do not have CSS files. That list is checked before the load/fetch of the CSS in the `loadBlock()` function. This method isn't ideal but is the best option for a few reasons:
1. We can't check in the browser whether the file exists first, without doing a fetch request. Doing that first would double the fetch requests, which would defeat the purpose.
2. We can't mark a block with a setting or data attribute to say it doesn't have CSS, since we don't have …
=> feat: remove fetch requests for empty css files

blocks/filter-group/filter-group.css, styles/base.css, styles/styles.css
- Remove `from` rgba syntax from meaningful elements
- Story: [ADB-254](https://sparkbox.atlassian.net/browse/ADB-254)
- After: https://rgbs--adobe-design-website--adobe.aem.page/
1. look at the page backgrounds, those are nice
2. look at the filters buttons on the ideas page and see if those are okay
3. add `disabled` to a button somewhere and see how that's going
5. look for instances of the transparency colors in the codebase, the link list and filter buttons are the main places
6. do it on dark mode or light mode, whichever isn't your normal jam
7. do it all in a second browser, probably safari, she can be a little finicky 
Note: we know there are still `from`s in the background gradients, but they break somewhat elegantly …
=> feat: expand browser support for most colors

blocks/article-header/article-header.js, blocks/filter-group/filter-group-functions.js, blocks/ideas/ideas-functions.js, blocks/ideas/ideas.js, blocks/recent-ideas/recent-ideas.js, scripts/helpers/buildArticlePage.js, scripts/helpers/fetchAndBuildIdeas.js, styles/global-blocks.css, styles/styles.css
Adds support for multiple article tags throughout the various blocks, including the ideas block and recent ideas. Multiple tags can be included separated by commas on an article page, and within the settings for the ideas blocks.
Supports multiple tags on the article pages using the new layout where they appear at buttons below the author bio. This replaces the eyebrow tag link from the top of the article header.
- Story: [ADB-260](https://sparkbox.atlassian.net/browse/ADB-260)
- After: https://feat-multiple-tags--adobe-design-website--adobe.aem.page/
2. Visit testing link.
3. Confirm multiple tags on articles is not causing any issues and these articles appear where they should on the …
=> feat: support multiple article tags

blocks/button-group/button-group.js, scripts/aem.js, scripts/scripts.js
- Adjust the function order to ensure blocks are fully decorated prior to cleaning up empty DOM elements
- Added a potentially unnecessary check to ensure we don't remove our aria-live region
- After: https://quick-fix--adobe-design-website--adobe.aem.page/
1. Review the "view all" buttons on the homepage and check that all buttons work as intended
1. Review the "button group" on the pattern library and check that all buttons work as intended
1. Take a breath to wish we had visual regression testing to catch this stuff 
1. Check that there's always an aria-live region on the page
1. Look out for stray divs
1. Make sure I didn't break your stuff, buddy
=> fix: placeholder rows are not removed prior to block decoration

blocks/recent-ideas/recent-ideas.js, scripts/helpers/fetchAndBuildIdeas.js
Add an optional value for the Recent Ideas block of "UseMetadataTags", for it to pull in the tags value from the current article page. Used for the article prefooter to show related stories/ideas. Also excludes the current page from list of fetched articles, so the same article you are on does not show in the list of related articles.
The article prefooter content has been updated to use this and the recent ideas block, instead of a manually entered card list.
- Story: [ADB-259](https://sparkbox.atlassian.net/browse/ADB-259)
- After: https://feat-related-prefooter--adobe-design-website--adobe.aem.page/
2. Visit multiple article pages on the PR testing link.
3. Confirm that ideas with the …
=> feat: recent ideas - option to pull tags from metadata

blocks/article-header/article-header.css, blocks/page-header/page-header.css, blocks/page-header/page-header.js, scripts/helpers/buildArticlePage.js, styles/base.css, styles/global-blocks.css, styles/styles.css
- Modify styling for h3 through h6 in articles
- Add what seemed to be gaps in `--spectrum-heading-size-*` tokens on screen size increase
- Ex: On a large screen, `--spectrum-heading-size-l` was larger than both `--spectrum-heading-size-xl` and `--spectrum-heading-size-xxl`
- Reflect design with typography breakpoints
- The Figma sheets represent a `max-width` approach, so fonts grow earlier than before
- Style tags heading on article pages
- Update Page Header styles to reflect changes in tokens
- Update Card styles such that the content font-size of Cards in a four-up layout grow with the screen
- Designs: [Figma](https://www.figma.com/design/QzvOszpLGT7fwSd6N7gaDW/Adobe-Design?node-id=1135-14473&t=nVliYDqHoSywXieG-1)
- Story: [ADB-249](https://sparkbox.atlassian.net/browse/ADB-249)
- …
=> fix: typography review

404.html, blocks/filter-group/filter-group-functions.js, blocks/ideas/ideas-functions.js, blocks/ideas/ideas.js, scripts/helpers/buildJobListingPage.js, scripts/helpers/index.js, scripts/scripts.js
- Adjust language for consistency: use "job listing" and "article" where possible. 
- Designs: [Figma](FIGMA_URL)
- Story: [ADB-271](https://sparkbox.atlassian.net/browse/ADB-271)
- After: https://glossary-updates--adobe-design-website--adobe.aem.page/
1. Check that Ideas and Careers render 
1. Check that a job post, like `/careers/r154528-sr-content-strategy-manager` renders
1. High five!
=> chore: adjust language of subpages to be consistent

404.html, blocks/article-header/article-header.css, blocks/article-header/article-header.js, styles/global-blocks.css, styles/styles.css
Shawn's site-wide feedback has been addressed. See validation for exact changes.
- Story: [ADB-272](https://sparkbox.atlassian.net/browse/ADB-272)
- After: https://fix-design-review-feedback--adobe-design-website--adobe.aem.page/
1. Open the [main preview site](https://main--adobe-design-website--adobe.aem.page/) and the [branch preview site](https://fix-design-review-feedback--adobe-design-website--adobe.aem.page/), we're doing some compare and contrast today
1. Verify the page header now has a `margin-block-end` value after the small-screen-cta block disappears at large screens
1. Navigate to `/careers/example-job-posting`
2. There is no longer additional `margin-block-start` on the `h1`, and there is less `margin-block-end` …
=> fix: address design review feedback

styles/global-blocks.css, styles/styles.css
Prevent fixed career CTA at bottom of screen from appearing when the screen height is too small, such as in landscape on a mobile device. This prevents the CTA from taking up too much of the screen. The CTA is still shown at the bottom of the page, in addition to also having another button at the top for the same action. This also improves the reported issue with 400% zoom.
- Story: [ADB-273](https://sparkbox.atlassian.net/browse/ADB-273)
- After: https://fix-cta-size--adobe-design-website--adobe.aem.page/
1. Visit testing link.
2. Confirm that CTA fixed to the bottom at `/careers/example-job-posting` is not appearing when the screen height is less than 40rem (640px). E.g. device simulator in landscape for common/listed mobile …
=> fix: remove display fixed from career cta for small viewport heights

styles/global-blocks.css
The card grid now handles both square and 4:3 aspect ratio images when they are used for articles. When the card grid item image and its content are stacked, a 4:3 aspect ratio with the `object-fit: cover` image within it is now used. The existing behavior remains for the breakpoints where the card image and its content are side by side. As a bonus, this change also improves how cards look while the images are loading in.
- Story: [ADB-289](https://sparkbox.atlassian.net/browse/ADB-289)
- After: https://feat-image-aspect-ratio--adobe-design-website--adobe.aem.page/
1. Visit testing link home page and Ideas page.
2. Test that the grid looks correct at all breakpoints on the homepage cards and Ideas page cards. When the image and …
=> feat: use set aspect ratio for card images

blocks/link-list/link-list.js
The job link list, which has a variant class and different content classes that make it appear as a different 2 column layout, was relying on all link list links starting with the domain name. Allow root relative linking for this logic, which will help with previewing the in progress content migration. In the future we may want to use another technique so the application of the jobs list styling is through an option and generally less fragile by relying on the URL.
- After: https://fix-jobs-list-relative-links--adobe-design-website--adobe.aem.page/
1. Using a relative job listing link starting with `/careers/` does not change the jobs link list to a different layout. This content is in `partials/jobs-list`. It should still be …
=> fix: allow jobs link list to have relative career links
